[package]
name = "bleh"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["barcode", "centroid", "colors", "tutorial", "particles", "swirly"]

[dependencies]
chrono = "0.4.22"
nannou = "0.18.1"
